### ISSUE TITLE
mempool missing input if client is shutdown in the 120 block validation period.

### ISSUE THREAD

**Issue by coderboo** [syscoin/syscoin1#1]
Solution: don't shut down your client during this period.

**Comment by dwasyluk** [comment]
Steps to recreate:
1. start mining
2. use a syscoin-service based tx
3. close the wallet BEFORE the tx gets any confirmations; do not stop mining
4. reopen wallet, attempt to start mining -> mempool crash

Have not tested this in 1.6b3 but was still reproducible as of 1.6b2.

**Comment by dwasyluk** [comment]
Fixed.
