### ISSUE TITLE
Offer name is getting converted to unicode in the output of some RPC commands

### ISSUE THREAD

**Issue by Snipsnoop** [syscoin/syscoin1#10]
In offerhistory (outside wallet) and in offerlist (inside of the wallet after purchasing an item) - the names of offers seem to be getting converted to unicode. For example offer guid '58af8423990635b200' when called: 
offerinfo 58af8423990635b200:
{
"id" : "58af8423990635b200",
"txid" : "ea502f7e23c5a00d5b9bda48b974674c4c07d53dae8cf23a8fcfb232f23829eb",
"address" : "STF1RLHVs11Tt3pNHNto5521BshLfLpWu5",
"expires_in" : 3717508,
"payment_address" : "STjQBuS7mrpxkFDPjzWXJQ1sPmTD6ZDVuC",
"category" : "Test",
"title" : "SaffronCoin",
"quantity" : "0",
"price" : 20.00000000,
"fee" : 88.00000000,
"description" : "",
"accepts" : [
{
"id" : "56f2c37f605ca01f",
"txid" : "ea502f7e23c5a00d5b9bda48b974674c4c07d53dae8cf23a8fcfb232f23829eb",
"height" : "4489",
"time" : "1408522133",
"quantity" : "1",
"price" : 20.00000000,
"paid" : "false"
}
]
}
BUT when calling offerhistory 58af8423990635b200:
[
{
"offer" : "58af8423990635b200",
"value" : "\u00AE\u009FR\u0088ybV\u00A3\u00C4\u0016_\u00F9\u00BE\u0095{\u00E9\u00FB\u00D7\u000B\u00C7",
"txid" : "ea502f7e23c5a00d5b9bda48b974674c4c07d53dae8cf23a8fcfb232f23829eb",
"address" : "STF1RLHVs11Tt3pNHNto5521BshLfLpWu5",
"expires_in" : 3717506
}
]
NOTICE THE UNICODE "value" instead of "Saffron". This also happens on offerlist for items the user has purchased.

**Comment by dwasyluk** [comment]
Cannot recreate with latest code, closing.
