### ISSUE TITLE
'My Certificates' tab needs a Transfer button

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#101]
Currently the only way to transfer a cert is to right-click on the cert to bring up the context menu. There should also be a Transfer button, like there is for the other options in the context menu.

**Comment by sysmca** [comment]
Also need an 'EDIT' button in the Selling tab.

**Comment by sebastien1234** [comment]
With latest build you should be able to close this issue @sysmca please retest when new build comes out.
