### ISSUE TITLE
Add additional currencies to price peg

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#104]
The price pegging option should also have the options of the three following currencies:

Chinese Yuan
Japanese Yen
South Korean Won

**Comment by dwasyluk** [comment]
These can be added through the SYS_RATES alias at any time, what we have in there right now is just what we use for testing, I can update it with more currencies or new rates for the current currencies. @sidhujag can you confirm that the UI elements in the wallet pull from the alias to populate things like the currency dropdown? If so we can close this...

**Comment by sebastien1234** [comment]
Bumping this @dwasyluk and @sidhujag if we want to attract china, we should really have CNY and others.

**Comment by sebastien1234** [comment]
closing #104 as opened in syscoin2 issue 16
