### ISSUE TITLE
unable to send message

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#105]
When I try to send a message or reply to a message, it gives me "Invalid syscoin address of fromalias"

Alias: sebastien

![image](https://cloud.githubusercontent.com/assets/7034589/11387646/a7871916-92fa-11e5-84f0-5a28d2409ea6.png)

**Comment by sebastien1234** [comment]
Prev pic was replying, this pic is for sending:

![image](https://cloud.githubusercontent.com/assets/7034589/11387673/ebe08188-92fa-11e5-909b-d44884b58f11.png)

**Comment by sidhujag** [comment]
Looks like sebastien alias is not found in the database, something went wrong with this alias upon creation. Do you have a debug.log?

**Comment by sebastien1234** [comment]
fixes #105 these encrypted messages are sweet!!
