### ISSUE TITLE
Weird Alias value bug

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#107]
First I created an alias without a value (although I thought there was a value but not sure).

Second I created a second alias with a value and now both alias show the same value:

![image](https://cloud.githubusercontent.com/assets/7034589/11388067/ab774582-92ff-11e5-9128-432ccc8dacbd.png)

**Comment by sebastien1234** [comment]
1st alias was "sebastien"

2nd alias is "Justin"

It appears that after the second alias validated, both values disappeared:

![image](https://cloud.githubusercontent.com/assets/7034589/11388076/ea5a5906-92ff-11e5-88a1-a19f0dbd4ed6.png)

**Comment by sidhujag** [comment]
I can't reproduce this, need clear steps from start to finish on this one.

**Comment by sebastien1234** [comment]
fixes #107 , Jag, whatever you did, you did it again!
