### ISSUE TITLE
Aliases should be case sensitive

### ISSUE THREAD

**Issue by Snipsnoop** [syscoin/syscoin1#11]
Aliases should be case-sensitive, currently the API allows for "Syscoin" and "syscoin". This should not be allowed.

**Comment by dwasyluk** [comment]
This is by design but I agree should be changed (thus removed bug label).

**Comment by dwasyluk** [comment]
@coderboo We'll need to figure out a solid way to implement this while respecting existing aliases that may be mixed-case-duplicates.

**Comment by dwasyluk** [comment]
For now we are keeping this as won't fix until there is some jsutification for the need. We just need to communicate clearly that aliases are case sensitive, register all the permutations you want to own if your concerned about others owning your aliases in a different "case".
