### ISSUE TITLE
Offers with Private Certificates not Transferring

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin1#110]
Alpha 4.2

Open Wallet A
Create Cert 1
Create Offer 1 with Cert 1 attached
Close Wallet A

Open Wallet B
Purchase Offer 1 with Cert 1 attached
Wait for confirmation.

Cert 1 is not transferred.
Close Wallet B

Open Wallet A
Certificate is still owned by Wallet A

**Comment by sidhujag** [comment]
do you see the offer accepted in wallet a under sold tab?

**Comment by Keyare** [comment]
Yes. Changed to private certs only.
