### ISSUE TITLE
Crash When Trying to Send Mesage

### ISSUE THREAD

**Issue by wazaweasel** [syscoin/syscoin1#116]
Opened wallet and tried to send message. After agreeing to pay to send message it crashed. Running windows 10. Screenshot of crash attached. Was able to recreate multiple times and never was successful in sending a message.
![error](https://cloud.githubusercontent.com/assets/12224312/11492530/1fec641e-97ac-11e5-8bfd-92f8bed6c5a6.png)

**Comment by dwasyluk** [comment]
This is fixed on OSX, @wazaweasel can you confirm on windows?
