### ISSUE TITLE
Search not working in marketplace

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#118]
After placing an offer, searching for it does not appear.

EX: offer ID: c2f19f4ed341f44b

Search Xbox, no results

**Comment by sidhujag** [comment]
Offers are private by default

**Comment by sebastien1234** [comment]
searching by GUID does not give results either, how can one find a private offer?

**Comment by sebastien1234** [comment]
@sidhujag can't change from private to public when trying to sell, option is "greyed-out"

**Comment by sebastien1234** [comment]
solved #118
