### ISSUE TITLE
No way to make a public offer

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#119]
marketplace/newoffer

the dropdown menu for private is greyed-out, unable to make a public offer:

![image](https://cloud.githubusercontent.com/assets/7034589/13309561/e7de5fa8-db4b-11e5-8d88-408a4808f421.png)

**Comment by sidhujag** [comment]
This is done by design because of offer impersonation. The other solution is to force users to make one offer or cert per
block so prev ones confirm but this seems like a weaker tradeoff
