### ISSUE TITLE
App Crashed, upon restart crashes again

### ISSUE THREAD

**Issue by wazaweasel** [syscoin/syscoin1#126]
Wallet froze when trying to do something with aliases and I essentially had to force quite it. When I opened the wallet up again it went through the process of verifying the blocks but when it got to 100% it said "Could not connect to best block" and shut down. 

Debug log is attached (had to zip to upload it)
[debug.zip](https://github.com/syscoin/syscoin/files/149635/debug.zip)

**Comment by sidhujag** [comment]
should be fixed on latest code, please retest and try to reproduce
