### ISSUE TITLE
Reseller Markup and discount bug

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#128]
When whitelisting an offer for a reseller, you have the option to give the reseller a discount. 

-Gave 10% discount to reseller (original price is $5), reseller should be purchasing at $4.50
-Reseller Marked-up price by 10%, so total amount should be $5.50

Instead of this, price was marked-up twice by 10$, sale value became $6.05 (10% twice)

Original offer: 451a3daabc4f7b0f
Reseller offer: ebfde3f28c43ed7f

**Comment by sebastien1234** [comment]
EDIT: 

I found the reason this is happening, as a reseller, every time I edit the reselling offer, it will mark it up by another 10%(IE: switching from public to private, switching again).

**Comment by sebastien1234** [comment]
@sidhujag since an offer is by default private, and you have to edit it to public, you are in-fact marking it up twice.

**Comment by sidhujag** [comment]
I noticed this.. i think i fixed it in latest code already

**Comment by sidhujag** [comment]
should be fixed in latest code, please retest on new net

**Comment by sebastien1234** [comment]
fixes #128
