### ISSUE TITLE
Buyer releasing escrow gives error

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#130]
Seller unable to release escrow, gets the following error:

![image](https://cloud.githubusercontent.com/assets/7034589/13377001/ac491be2-dd97-11e5-9aad-f6a5785d111e.png)

Escrow is able to release.

**Comment by sebastien1234** [comment]
Escrow ID: 2ac8a5095fc74e0e
Offer ID: 496f537340c5624a

**Comment by sidhujag** [comment]
if already released aeller must escrow release to get coins,.. buyer or arb already released before this?

**Comment by sidhujag** [comment]
oops misread, you have debug log? can you reproduce?

**Comment by sebastien1234** [comment]
No attempted a few times to reproduce and not getting error, must have been a mistake. closing ticket

**Comment by sidhujag** [comment]
was a cert involved, whitelist involved? intermittent bugs are harder to crush

**Comment by sebastien1234** [comment]
must have been user error. closing #130
