### ISSUE TITLE
Editing offer does not allow you to change the currency type

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#133]
marketplace/selling/edit offer:

Editing an offer does not allow you to change the currency type (is greyed out),you should be able to.

![image](https://cloud.githubusercontent.com/assets/7034589/13377255/10d8a132-dda1-11e5-9217-cb9636494c5b.png)

**Comment by sidhujag** [comment]
can't change currency right now by design, feature request this one.

**Comment by sebastien1234** [comment]
closing #133 as moved to issue 20 in /syscoin2
