### ISSUE TITLE
bottom design missing on a few screens

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#135]
the bottom design (wavey blue lines) shows on the "overview", "send", "receive", "transactions", but is missing on the "aliases", "messages", "escrow", "marketplace", "certificates" buttons to make the wallet consistent in it's design.

**Comment by sidhujag** [comment]
im not seeing this

**Comment by sebastien1234** [comment]
1st image is cutoff(transactions):

![image](https://cloud.githubusercontent.com/assets/7034589/13384834/b0be06a8-de67-11e5-9b96-a15f29fc599e.png)

2nd, 3rd, 4th, 5th images you don't see it at all, even at full screen(aliases, messages, escrow, marketplace, certificates):

![image](https://cloud.githubusercontent.com/assets/7034589/13384841/c83577ee-de67-11e5-97ed-40e768f9b794.png)

![image](https://cloud.githubusercontent.com/assets/7034589/13384855/01156ba0-de68-11e5-8bf1-ec2588c79955.png)

![image](https://cloud.githubusercontent.com/assets/7034589/13384856/04457d2e-de68-11e5-939e-50094bca0992.png)

![image](https://cloud.githubusercontent.com/assets/7034589/13384858/0841ca90-de68-11e5-8c39-fd6f96515ce7.png)

![image](https://cloud.githubusercontent.com/assets/7034589/13384861/0c39ae9c-de68-11e5-943e-cb479e1f3c9e.png)

**Comment by sidhujag** [comment]
This about a days work alone just because of qt issues. Leaving it for this next build unless we really want it.

**Comment by sebastien1234** [comment]
closing #135 as moved to issue 21 in /syscoin2
