### ISSUE TITLE
'Please select an alias you own' - this is confusing

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#141]
Any form that requires you to enter your alias has confusing and inconsistent text next to it.

_'Please select an alias you own'_ - implies you can select aliases you don't own?

The drop down list is only populated by your own aliases, so text should just say 'Select Alias'

Maybe this text could be the first item in the drop down list?

Also it shouldn't be red - this suggests you've submitted the form and an error has been thrown.

**Comment by sidhujag** [comment]
Dropdown should probably have "Select Alias" as the first item.

**Comment by sidhujag** [comment]
please retest in latest build
