### ISSUE TITLE
Transferred Aliases don't show up in blank searches but do if you search directly

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#144]
I transferred the following Alias to johnp

Here_have_an_alias

It doesn't show up when I search with an empty search field (ie display all Aliases) but it does when I search specifically for it (e.g search term 'Here')

**Comment by sidhujag** [comment]
did it confirm? after confirm it should show up, otherwise its a buig. Do other aliases show up on empty search?

**Comment by sysmca** [comment]
Yeah it confirmed. Look for `Here_have_an_alias` in a blank search, then search for it by name

**Comment by sysmca** [comment]
Another alias I created (but didn't transfer this time) is WHOLESALER - it also only shows up in the search results when I search for it directly

**Comment by sysmca** [comment]
Replicated with alias ID 'TESTING_XFERED_ALIAS'

Do a blank search, it doesn't show up. Direct search does. (for me at least)

**Comment by sidhujag** [comment]
how many search results did you select? did you try with 100?

**Comment by sysmca** [comment]
okay it show up if I select 100.

But there's something else wrong here - the a-z sorting doesn't seem to work if I select 25 results. Well it does, but it excludes some results.

Steps:
1. do a blank search with 100 results
2. observe the alias `'Here_have_an_alias'` in the results list
3. do a blank search with 25 results
4. `'Here_have_an_alias'` is not there
