### ISSUE TITLE
Price pegging not working when purchasing Offer?

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#145]
I bought a Syscoin tee for $21.99 and the Accept Offer popup said I'd be charged 59155 SYS - does the conversion need to be applied to the price pegging or is it just because we're on the testnet?

**Comment by sidhujag** [comment]
That sounds about right, current sys_rates has the USD to SYS value set to about 2690.1.. so it shows the amount of SYS you will pay. We will have a bot running soon which will update prices in sys_rates properly

**Comment by sidhujag** [comment]
we need a more descriptive popup stating the fiat value and converted sys value to be charged
