### ISSUE TITLE
Purchase cost does not display fraction amounts

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#150]
I purchased a pen that cost 0.1 SYS - the Accept Offer popup said I was purchasing it for 0 SYS

![accept syscoin offer](https://cloud.githubusercontent.com/assets/15713199/13429650/22147e02-dfb9-11e5-9053-9cdf19097108.png)

**Comment by sidhujag** [comment]
retest in latest build, uses precision defined in sys_rates for sys prices
