### ISSUE TITLE
Suggestion: Tabs should auto-refresh when you select them

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#151]
It would be good if when you select a tab it automatically refreshes. Since many tabs require you to update them anyway to see the latest state of the blockchain.

I think all tabs should clear/refresh when you select them actually. Much tidier navigation experience imo

**Comment by sidhujag** [comment]
I did this but removed it because I made it so that services show up right away without confirmation, maybe good enough please try in new build
