### ISSUE TITLE
Wholesaler quantity doesn't update when reseller sells an item

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#152]
I made a 'wholesaler' identity and whitelisted a 'reseller' to sell my pens at a 30% discount.

Quantity of wholesaler's pens was 100

Reseller listed the pens via resell option, and quantity is also 100, as expected.

I used a third identity 'Buyer01' to purchase one pen

Quantity of the Reseller's listing updated to 99, but quantity of Wholesaler's listing stayed 100

![wholesaler_quantity_update](https://cloud.githubusercontent.com/assets/15713199/13429923/7ab6a994-dfba-11e5-8ed5-6dd298cfafc2.png)

**Comment by sysmca** [comment]
Hmm it looks like the exclusive resell whitelisting I set up for Reseller didn't work either. All funds from the sale went to the Reseller, 70% should have gone to Wholesaler as per the whitelist settings.

I transferred the certificate linked to the whitelist entry to the Reseller fine.

**Comment by sidhujag** [comment]
we found the second accept wasnt happening yet to track it down cause we dont have the debug info in the debug log
