### ISSUE TITLE
Scaling of the application

### ISSUE THREAD

**Issue by marijnbent** [syscoin/syscoin1#153]
The minimum width and height are causing some issues. When my screensize (Macbook 13 inch) is at its normal setting, some buttons and vital information are cut of. The application should adjust to the users screen.

**Comment by freedom77** [comment]
I'm having the same issue with the size of the application. It's too big for my 14" laptop screen. I'm using Windows 7. There's no way to adjust the width or height and the buttons at the bottom of the app were hidden.

**Comment by sebastien1234** [comment]
@marijnbent and @freedom77 can you please provide screenshots and advise at what resolution your screens are set to? (ie: 800X600) Thanks!

**Comment by freedom77** [comment]
@sebastien1234 
Screen resolution is set to: **1366 x 768**
This is the maximum and recommended resolution for my system. (See screenshot):
![syscoin beta 2 screenshot](https://cloud.githubusercontent.com/assets/12694272/13455491/9f439fc4-e055-11e5-8297-6adc5d6c6a04.jpg)

**Comment by freedom77** [comment]
Just to reiterate, the app doesn't let me adjust the height or width, it seems to be fixed, and it's too big for my screen. The buttons at the bottom are still hidden. I need to move the whole gui up as far as possible to see the tops of the buttons.

**Comment by dwasyluk** [comment]
This is a legit issues we'll be fixing, we noticed this in testing as well on some smaller resolutions. We'll be adjusting this so the _minimum supported resolution is 1024x768_, anything smaller is not really modern and would require quite a bit more work to make the UI layout "work" for those smaller dimensions without scrollbars all over the place.

**Comment by marijnbent** [comment]
Well the original raspberry pi display is smaller :-). I think those should
be usable too

Op wo 2 mrt. 2016 om 18:21 schreef Dan W notifications@github.com

**Comment by dwasyluk** [comment]
You have the screen dimensions for the pi? Maybe we can make something work :)

**Comment by marijnbent** [comment]
There are different ones, but one is with the dimensions 320x240. The
official 7 inch is 800x480
Op wo 2 mrt. 2016 om 18:29 schreef Dan W notifications@github.com

**Comment by dwasyluk** [comment]
Wow 320x240 is like... phone resolution. We will try though, you know of any other coin wallets that support this size resolution well? Might be a good reference, thanks.

**Comment by sidhujag** [comment]
The top of the window should allow you to resize it to become smaller. Seems sometimes it gets stuck on a big window, try to close and open again and try to resize from the top see if it gets smaller. I noticed it getting down to around 500px wide.

**Comment by sebastien1234** [comment]
I think the issue is the escrow tab, the wallet fits to the buttons on that screen. The wallet will let you resize but only down to fit the buttons of the screen that has the most buttons (Escrow tab)

![image](https://cloud.githubusercontent.com/assets/7034589/13556200/9593b46a-e3a1-11e5-9f8d-fb540496d162.png)

If we could make those buttons smaller or have two lines for them, then I think it would help the resizing 

I have a 23 inch monitor and the wallet takes up most of the screen even at it's smallest size.
