### ISSUE TITLE
Offer should be removed from Selling tab when quantity reaches zero

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#154]
I sold all stock of an item but the item is still listed in my Selling tab
![selling_tab_quantity_zero](https://cloud.githubusercontent.com/assets/15713199/13474853/d118105e-e0b7-11e5-81ea-35c8707cface.jpg)

**Comment by sidhujag** [comment]
not fixing this, havent defined rquirements

**Comment by sebastien1234** [comment]
There's definitely a benefit to keeping record of these offers such as being able to replenish your stock by changing quantities, however, @sidhujag we discussed this on the last call and there would be a benefit to having two sections here and having all offers that are at a 0 quantity in a separate section(archived).

**Comment by sidhujag** [comment]
added a checkbox for showing sold out offers in selling tab
