### ISSUE TITLE
Change "Value" name. 

### ISSUE THREAD

**Issue by Seven7Sevin** [syscoin/syscoin1#157]
Request you consider changing the word Value, under Alias, to something more understandable to mainstream users. Also provide some use case examples - Description of a product or whatever.

**Comment by dwasyluk** [comment]
Any suggestion in terms of label? Value comes from the domain namespace where DNS records have a name and value.

**Comment by Seven7Sevin** [comment]
Ummm.....I got nothin. I saw quite a few slack questions like, "What goes
in the value space." Indicated the average non-tech user might inundate you
with the same question. How about Quick Look? Short Description? Taxonomy?
Details? Additional Information? Christ, those all suck. Sorry. Or, how
about defining what "value" means when someone hovers over the word. Maybe
a popup that says "This is where you can put a brief description or
anything you want"?

**Comment by Seven7Sevin** [comment]
You guys fixed 97 issues/requests on SysGit already? Hot damn. Working like
a beaver who married a bee hive.

**Comment by sidhujag** [comment]
i already have a plan fore this.. its public profile information and there is also private profile information

**Comment by Seven7Sevin** [comment]
That's exactly what I was just going to suggest! ;-)
