### ISSUE TITLE
Data service help and functions are not analagous to aliases

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#18]
The alias and data commands should be analagous with the exception of data having a filename property and holding more data. Right now now only are there missing commands in the data subset, but some data commands refer to aliases and aren't even documented in help. ie: datahistory

OUTPUT:
20:25:24
￼datahistory

20:25:24
￼aliashistory <name>
List all stored values of an alias.
(code -1)

**Comment by sidhujag** [comment]
removed data aliases
