### ISSUE TITLE
Only display transactions I "own" or have "accepted" in offerinfo

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#26]
After several people have accepted an offer via offeraccept+offerpay. In offerinfo if I am looking at an offer NOT owned by me (my wallet) which I have performed offeraccept+offerpay against I should only be able to see the "accepts" performed by me / my wallet.

If I perform "offerinfo" and I am looking at the offer from the wallet which OWNS the offer, ALL accepts are displayed.

**Comment by JohnDorien1** [comment]
I guess this is not a proper solution in terms of public blockchain.
Better way would be an auto-encrypted value and offerinfo only decryptable by the owners of the offer and the one doing offeraccept himself.

**Comment by sidhujag** [comment]
do we want this now that we have encryption?
