### ISSUE TITLE
Data Aliases showing on the My Aliases and Search Aliases QT wallet's tabs

### ISSUE THREAD

**Issue by xpansiv** [syscoin/syscoin1#28]
I checked it several times. It shows the file field of the data alias on the Value field of the QT tables.

![dataalias_on_myaliasestab](https://cloud.githubusercontent.com/assets/6384936/4514738/c27ca88a-4b89-11e4-9f0b-640b550cb7ec.png)

**Comment by sidhujag** [comment]
This is per design

**Comment by dwasyluk** [comment]
can we use the filename property (only present on data alias) to differentiate the two types of aliases?

**Comment by sidhujag** [comment]
removed data aliases
