### ISSUE TITLE
Service fee schedule does not seem to follow the prescribed schedule

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#35]
The service fee schedule should be running on: https://docs.google.com/spreadsheets/d/1x8dv0pGyRCeT8aXIEQpgNiq0ENxJKwEO_PmZqnxJERk/edit?usp=sharing

But running DataActivate with different payloads always costs the same amount - it should change based on size in kb of the data as reflected in the schedule.

**Comment by sidhujag** [comment]
service fee is based on pegged alias now
