### ISSUE TITLE
Deterministic address populated in address book when "address" field is left blank on add new address operation

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#41]
If while adding a new address to your local address book you omit the "address" field in the form which contains "label" and "address" the QT wallet will generate an address deterministically resulting in "SQaRyNW6VdKHQnk4sREVBFNX6SdN8q5T4b". 

The QT wallet should not allow the addition of a new address when the "address" field is still blank.

Steps to recreate:
1. Go to address book
2. Click "create new address"
3. Leave both fields blank and click "Ok" notice new address SQaRyNW6VdKHQnk4sREVBFNX6SdN8q5T4b is added to address book in background
4. Close and reopen "add new address" and click "Ok" again, note the error saying "The entered address "" is already in the address book." because the generated address is always the same.
5. Delete the generated address and try adding a blank address again and the same address [SQaR] is added the address book.

**Comment by sebastien1234** [comment]
fixes #41

**Comment by dwasyluk** [comment]
Fixed.
