### ISSUE TITLE
Marketplace "accept and pay for offer" Syscoin spelling

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#43]
Under Marketplace tab "accept and pay for offer". Text indicates "accept and purchase this offer, Syscoins will be used to complete the transaction". Syscoin should not have an 's'. Should also probably remove the "Accept and Purchase" and just change to "Purchase". 

New suggested text: "Purchase an offer. Syscoin will be used from your balance to complete the transaction"

**Comment by dwasyluk** [comment]
verified fixed, closing.
