### ISSUE TITLE
Total amount charged does not include fee

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#51]
Marketplace/Purchase Offer/Accept Offer:

"Are you sure you want to purchase XXX? You will be charged YYY SYS"

The YYY Amount indicated in the line above does not include the fee.

![screenshot 2015-10-03 12 44 41](https://cloud.githubusercontent.com/assets/7034589/10263933/99329bf8-69cc-11e5-8ef9-9300a7ef6da5.png)

**Comment by sidhujag** [comment]
There is no syscoin service fee on payment, you may talking about the network fee? That can be 0 but you may not get included in a block, its the fee paid to the miner. It's usually not included in price quotations.
