### ISSUE TITLE
Certificate data field does not appear to accept all ASCII characters or interprets them differently

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#53]
1. Renamed a JPG file to TXT file to get it's data via edit
   ![screenshot 2015-10-09 01 04 22](https://cloud.githubusercontent.com/assets/7034589/10386183/b25b93ba-6e21-11e5-94ad-6e7419225165.png)
2. Copied TXT content to Certificate data and created the certificate dolphin.jpg
3. Waited for certificate to validate
4. Edited Certificate to see the content of the data
   ![screenshot 2015-10-09 01 06 23](https://cloud.githubusercontent.com/assets/7034589/10386205/fc54f07e-6e21-11e5-8c6a-be8c81b2c597.png)
5. Noticed some characters are not transferring properly comparing both documents
6. Tried copying the data from the certificate to a TXT file and renaming it a JPG, file is not readable.

**Comment by sidhujag** [comment]
Let's not attach binary data to the blockchain, its wasteful, better to just use hashes.

**Comment by sebastien1234** [comment]
Closing as we will not use certs for binary data
