### ISSUE TITLE
Certificate data field shows wrong info

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#58]
When searching a certificate that you do not own, the "DATA" field does not show the actual data of the certificate but instead shows the same info as the "Title" field.
![screenshot 2015-10-17 23 07 05](https://cloud.githubusercontent.com/assets/7034589/10562296/c15e4c46-7523-11e5-9083-2974855163e6.png)

**Comment by dwasyluk** [comment]
Confirmed fixed.
