### ISSUE TITLE
Use certs to send encrypted messages

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#59]
In an effort to use Shade as an all-in-one service to buy and sell items, it would be beneficial to include an encrypted certificate transfer function to send and receive messages regarding a sale(pre-sale, while making the pucharse to mask address info, post-sale)

**Comment by sidhujag** [comment]
Sebastien I have done this for beta3 can you check and close? Also did cert encryption

**Comment by sebastien1234** [comment]
fixes #59 Jag, you've done it again!!!
