### ISSUE TITLE
Marketplace GUI suggestion: Add pictures

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#60]
It would be really beneficial for us to be able to to show an image of the item being sold. 

Perhaps there is a way to program the GUI that if you put a URL (IE: IMGUR) of the image on the first line of the description, it would show that image.

**Comment by sidhujag** [comment]
Sebastien I have included this in beta3, please confirm and close

**Comment by sebastien1234** [comment]
fixes #60 AWESOME!!!
