### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#65]
It would be really beneficial for someone to be able to put multiple images on the marketplace offer (with arrows on the sides of the image to navigate if there's more than 1.

**Comment by sidhujag** [comment]
Imo we dont need to show more than one.. It will take longer to load and its a reference client.. Better to do this via web blockmarkets

**Comment by sebastien1234** [comment]
@sidhujag : The idea would be to put arrows on the side of the picture to click to the next picture, so it would only load one picture at a time, but perhaps it's a lengthy fix which is not a priority.

**Comment by sidhujag** [comment]
won't do, tried it.
