### ISSUE TITLE
After a certain quantity, offer is interpreted as sold-out

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#72]
originates: Marketplace/selling/new offer
problem detected: marketplace/search/GUID:2a45495501334d41

Not sure what amount is but after a certain amount entered in an offer, it will be interpreted as sold out and buyers are not able to purchase

https://www.dropbox.com/s/ichhxf72k4iv5j5/Screenshot%202015-10-25%2023.59.32.png?dl=0

**Comment by sebastien1234** [comment]
There should be a way that once user tries to sell this amount, that he will be told that this "Quantity exceeds allowed amount of (enter limit amount), please submit multiple offers"

**Comment by dwasyluk** [comment]
@sidhujag is this related to the type of the qty value?

**Comment by sidhujag** [comment]
changed the internal type from uint64 to uint, was a type mismatch... dont need uint64 for qty

**Comment by dwasyluk** [comment]
Seems fixed but verification is blocked by #84

**Comment by sebastien1234** [comment]
fixes #72
