### ISSUE TITLE
cannot see full text on description

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#80]
Marketplace/buy/description:

-Scroll bar does not work.
-Will show a limit of text(about half in this case, and cut off the last line, even full screen on a 23 inch) 

I think it would just require the scroll bar to work as a fix.

Cannot see full content of text ,
![image](https://cloud.githubusercontent.com/assets/7034589/10777631/d0a086e2-7cf3-11e5-9e26-ecc7dd6d9766.png)

**Comment by dwasyluk** [comment]
issue can be replicated on OSX, additionally the text in the fields cannot be selected for copy/paste purposes.

**Comment by dwasyluk** [comment]
Fixed on OSX (text selection, copy+paste, and scrolling), closing.
