### ISSUE TITLE
should not be able to edit certain fields

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#87]
Issue #74 was resolved, however now you can actually edit the fields and are able to key in different things, it doesn't affect the offer or it's acceptance obviously, but should not be editable. 

Also suggestion to Grey-out non editable fields, and leave only Notes white

https://www.dropbox.com/s/1e90rl602iavkai/Screenshot%202015-10-29%2001.46.39.png?dl=0

**Comment by sidhujag** [comment]
you won't be able to copy and paste when they are non editable.. how about leaving the description and cert field editable so they can copy it?

**Comment by sebastien1234** [comment]
Awesome, is it possible to grey-out all fields except for notes? @sidhujag

**Comment by sidhujag** [comment]
but then they can't copy description which was another bug... if its read only you cant copy the text it seems.

**Comment by sebastien1234** [comment]
sorry I meant grey-out all fields except for notes/description and cert ID. @sidhujag

**Comment by sidhujag** [comment]
ok, done in latest push

**Comment by sebastien1234** [comment]
fixes #87
