### ISSUE TITLE
if you have a certificate, you are forced to sell one in an offer. Can try to sell same cert multiple times.

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#88]
Marketplace/selling/new offer:

When I create a new offer and I own a certificate, there is no option in the drop down to not sell a certificate, it defaults to your first one or you can select another. 

It should default to "No certificate included"

![image](https://cloud.githubusercontent.com/assets/7034589/10834222/e01b09dc-7e6d-11e5-941e-371ed41f82e8.png)

This also made me realize that there is another problem:

Although you cannot sell a certificate more than once, you can offer it more than once, I did not realize it was defaulting to a certificate when making my offers so I ended up putting for offer the same certificate many times. One should not be allowed to attempt to sell the same certificate twice or more.

See image below, cert "01aadf.." is being sold 3 times.

https://www.dropbox.com/s/pmtjheryyok0xwd/Screenshot%202015-10-29%2018.51.10.png?dl=0

**Comment by sidhujag** [comment]
first part related to issue #84 which was already fixed, second part is valid

**Comment by sebastien1234** [comment]
fixes #84
