### ISSUE TITLE
Pegging conversion displays in scientific notation

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#90]
When creating an offer for sale at a price of 678 USD the GUI displayed the converted SYS cost as "1.82389e+06 SYS" in the confirmation. This is confusing as normal users do not expect prices to be in scientific notation.

**Comment by sidhujag** [comment]
that is 1.82 million SYS, you only had 1mil SYS you said?

**Comment by dwasyluk** [comment]
You are correct. This is what i get for logging issues at 3am. Updated to simply be a correction to not show price in scientific notation.

**Comment by sidhujag** [comment]
did you have 2 million or 1 million sys at the time?

**Comment by dwasyluk** [comment]
Verified.
