### ISSUE TITLE
Dano's test offer on Blocktalk no longer showing image

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#94]
Since latest push, @dwasyluk 's test that he performed on blocktalk no longer shows the picture. I tried to create various offers to duplicate but was not able to; Dano's GUID: 9d1f8ed514ff4f30

![image](https://cloud.githubusercontent.com/assets/7034589/10867327/f33921aa-8031-11e5-840a-5a37395796d1.png)

**Comment by sebastien1234** [comment]
Clicking on image window still works but it will not display preview on marketplace/buy.

**Comment by dwasyluk** [comment]
Working here in 2 clients, closing.
![screen shot 2015-11-01 at 11 38 41 am](https://cloud.githubusercontent.com/assets/987186/10869977/28cafc70-808d-11e5-85b3-f18cfc4845c3.png)

**Comment by sebastien1234** [comment]
That's not the GUID I quoted, GUID 9d1f8ed514ff4f30 is still not showing a pic

**Comment by sidhujag** [comment]
Dan can you try the guid seb is talking about?

**Comment by dwasyluk** [comment]
This works using GUID 9d1f8ed514ff4f30. Not closing just in case Seb wants me to try a diff route?
![screen shot 2015-11-01 at 9 55 09 pm](https://cloud.githubusercontent.com/assets/987186/10873473/50ddd4b6-80e3-11e5-9477-bc14b87e3f95.png)

**Comment by sebastien1234** [comment]
Dunno, I'm still not seeing a pic unless I click on it..Are you using the same wallet that made the offer to test?

**Comment by sidhujag** [comment]
it works for me, perhaps your network is cutting off the connection for some reason, it loads just fine for me on same and another wallet. I'm on windows too.

**Comment by sebastien1234** [comment]
@dwasyluk @sidhujag can you make a new offer with a pic, the only other offers w/pics I see are my own(other than this one)

**Comment by sebastien1234** [comment]
I figured it out, it appears I am unable to see images if HTTPS is used for the pic. I was able to duplicate @dwasyluk 's offer and got the same problem d521b3930f3a7710: 
![image](https://cloud.githubusercontent.com/assets/7034589/10941678/8d20a2b6-82da-11e5-8a01-54cff1e4733f.png)

I then tried an offer that has the exact same link but without the secure HTML (only HTTP) and it worked fine:

![image](https://cloud.githubusercontent.com/assets/7034589/10941714/ab6db86c-82da-11e5-928d-0347a9408d8d.png)

**Comment by sebastien1234** [comment]
Fixed #94 in latest build
