### ISSUE TITLE
Cert-linked offer quantity should not be editable

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#95]
Offers linked to certs need to have a fixed qty of 1. The erroneous cert-offer from Blocktalk was sold but the cert was not transferred (bug which I'm now testing). I am able to edit this cert-linked offer and edit the qty to whatever i want even tho its still linked to a cert. Anytime a certificate is selected the qty dialog should go into read-only mode with a fixed value of 1 that cannot be edited.

_Note:_ Although I was allowed to enter "200" as qty, once the tx confirmed the offer only showed "1" as qty. Not sure if this is a protection mechanism, a corrective mechanism, or a lucky error.

Recreate:
1. create cert-linked offer
2. buy offer as different node
3. edit offer as original node and change qty from 0 to 200

**Comment by sidhujag** [comment]
this was because the cert wasn't transferred (bug), so if the cert got transferred you wouldn't be able to edit the offer (because the linked cert isn't yours anymore), retest
